codecov:
  branch: master
ignore:
  # Db migration allowed for production only
  - "apps/db-migration"
  # Disable on project entry point
  - "**/main.rs"

  #
  #
  # Program specific
  #
  #

  #
  # Those scripts are never used in non-production environments, so the code coverage never runs it.
  #
  - "apps/server/src/auth/auth_controller/get_tokens.rs"
  - "libs/utils/src/redis.rs"
  - "libs/utils/src/config.rs"
  # Relation is never used in test
  - "libs/core/src/repository/database/entities"
  - "libs/core/src/utils/db_tools.rs"
  - "libs/core/src/service/file/provider"
