version: "2"

services:

  server:
    container_name: discuz_server
    build: ./
    restart: unless-stopped
    ports:
      - 3100:7800
    command: cargo run --release --bin discuz-server
    logging:
      driver: "json-file"
      options:
        max-size: "200k" # 200kb
        max-file: "2"
    ulimits:
      core: 1024

  mysql:
    container_name: discuz_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=discuz
      - MYSQL_USER=discuz
      - MYSQL_PASSWORD=discuz
      - MYSQL_DATABASE=discuz

networks:
  default:
    external:
      name: discuz
