[env]
RUN_MODE = "testing"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dev]
workspace = false
env = { RUN_MODE = "development", RUST_BACKTRACE = "0" }
command = "cargo"
args = ["watch", "-x run"]

[tasks.test]
env = { RUN_MODE = "testing", RUST_BACKTRACE = "0", RUSTFLAGS  = "-A unused_imports" }
command = "cargo"
args = ["nextest", "run", "--no-capture"]
