version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

workflows:
  Main:
    jobs:
      # - Upload Code Coverage
      - Spell Check
      - Format
      - Build Binary
      - Lint:
          requires:
            - Build Binary
      - Unit Test:
          requires:
            - Build Binary
      - Database Migration Test:
          requires:
            - Build Binary
      - Integration Test:
          requires:
            - Unit Test
            - Database Migration Test
      - Upload Code Coverage:
          requires:
            - Integration Test

jobs:
  # Linting and Formatting related

  Lint:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          command: cargo clippy --tests --examples --all-targets --workspace

  Format:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          command: rustup component add rustfmt
      - run:
          command: cargo fmt --all -- --check

  Spell Check:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          command: sudo npm install -g cspell@latest
      - run:
          command: cspell "**"

  # Build and save the binary into the workspace

  Build Binary:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: cargo build --bin discuz-server
      - run: cargo build --bin db-migration
      - persist_to_workspace:
          root: .
          paths:
            - target/*

  # Testing

  Unit Test:
    docker:
      - image: cimg/rust:1.65.0
    environment:
      RUN_MODE: testing
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          command: cargo test

  Database Migration Test:
    docker:
      - image: cimg/rust:1.65.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: discuz
    environment:
      RUN_MODE: ci
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          command: cargo run --bin db-migration

  #

  Integration Test:
    docker:
      - image: cimg/rust:1.65.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: discuz
    environment:
      RUN_MODE: ci
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: cargo run --bin db-migration
      - run: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run: sudo npm i -g newman
      - run: nohup ./target/debug/discuz-server ./target/debug/discuz-server
      - run: ./tests/wait-for-readiness.sh
      - run:
          working_directory: ./tests
          command: ./api-test.sh

  #
  Upload Code Coverage:
    docker:
      - image: cimg/rust:1.65.0
    environment:
      RUN_MODE: ci
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
            name: Install Tarpaulin
            command: cargo install cargo-tarpaulin
            environment:
              RUSTFLAGS: --cfg procmacro2_semver_exempt
      - run:
          name: Generate coverage report
          command: cargo tarpaulin --out Xml --all-features
      - codecov/upload
