version: 2.1

workflows:
  Main:
    jobs:
      - Linting
      - Testing
      - Formatting
      - Migration Test
      - Spell Check
      - Integration Test:
          requires:
            - Linting
            - Testing
            - Formatting
            - Migration Test
            - Spell Check

jobs:
  Linting:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          command: cargo clippy --tests --examples --all-targets --workspace

  Testing:
    docker:
      - image: cimg/rust:1.65.0
    environment:
      RUN_MODE: testing
    steps:
      - checkout
      - run:
          command: cargo test

  Migration Test:
    docker:
      - image: cimg/rust:1.65.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: discuz
    environment:
      RUN_MODE: ci
    steps:
      - checkout
      - run:
          command: cargo run --bin db-migration

  Formatting:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          command: rustup component add rustfmt
      - run:
          command: cargo fmt --all -- --check

  Spell Check:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          command: sudo npm install -g cspell@latest
      - run:
          command: cspell "**"

  Integration Test:
    docker:
      - image: cimg/rust:1.65.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: discuz
    environment:
      RUN_MODE: ci
    steps:
      - checkout
      - run: cargo run --bin db-migration
      - run: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run: sudo npm i -g newman
      # - run:
      #     working_directory: ./tests
      #     command: ./api-test.sh

