# Default settings
run_mode = "testing"

[database]
hostname = ""
username = ""
password = ""
port = 3306
database = ""

[app]
port = 3100

[amazon]
region = "ca-central-1"

[amazon.cognito]
user_pool_id = ""
domain = ""
client_id = ""
redirect_uri = "http://localhost:3000"

[amazon.s3]
bucket = ""
